name: 'urban_pulse'
version: '1.0.0'
config-version: 2

profile: 'urban_pulse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  urban_pulse:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      core:
        +materialized: table
      analytics:
        +materialized: table

vars:
  start_date: '2024-01-01'
  city: 'Mumbai'
